services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   ports:
     - 5174:5174
   entrypoint: ["/bin/sh", "-c", "npm run dev -- --host"]
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
